modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/DynamicTreesTeam/DynamicTrees-PrimalMagick/issues"

[[mods]]
modId = "dtprimalmagick"
version = "${file.jarVersion}"
displayName = "Dynamic Trees for Primal Magick"

updateJSONURL = "https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/PrimalMagick.json?raw=true"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-primal-magick"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Primal Magick
'''

[[dependencies.dtprimalmagick]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtprimalmagick]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.dtprimalmagick]]
modId = "dynamictrees"
mandatory = true
versionRange = "[1.3.0-BETA10,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtprimalmagick]]
modId = "dynamictreesplus"
mandatory = false
versionRange = "[1.2.0-BETA2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.dtprimalmagick]]
modId = "primalmagick"
mandatory = true
versionRange = "[4.0.0,4.1.0)"
ordering = "AFTER"
side = "BOTH"